"use client";
import { useRef, useState } from 'react';
import { ArrowRight, Clock3, Download, GitCompareArrows, History, LockKeyhole, Plus, RotateCcw, Save, Trash2, Upload } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { type Project, projectSchema, validate } from '@/lib/robot-model';
import { compareProjects, historyFile, parseHistory, restoreCheckpoint, nextCanId, HISTORY_LIMIT, type Checkpoint, type DesignChange, type MechanismAddition } from '@/lib/development';
import type { DevelopmentState } from '@/hooks/use-development';
import { download } from '@/lib/zip';
import { toast } from 'sonner';

export function ChangeList({ changes, setTab }: { changes: DesignChange[]; setTab?: (s: string) => void }) {
  return changes.length ? <div className="design-changes">{changes.map((c, i) => <div className="design-change" key={i}><span className={'change-kind ' + c.kind}>{c.kind}</span><div><b>{c.name}</b><small>{c.area}</small>{c.details.length > 0 && <ul>{c.details.map((d, n) => <li key={n}>{d}</li>)}</ul>}</div>{setTab && <button className="text-button" onClick={() => setTab(c.area)}>Edit <ArrowRight size={14} /></button>}</div>)}</div> : <p className="development-empty">No design changes. Bench-check confirmations and feed-check timestamps are excluded from this comparison.</p>;
}
export default function DevelopmentView({ project, state, setTab }: { project: Project; state: DevelopmentState; setTab: (s: string) => void }) {
  const [name, setName] = useState(''), [notes, setNotes] = useState(''), [selected, select] = useState('');
  const [restoring, setRestoring] = useState<Checkpoint | null>(null), [removing, setRemoving] = useState<Checkpoint | null>(null), [adding, setAdding] = useState(false);
  const [addition, setAddition] = useState<MechanismAddition>({ name: '', controller: 'none', can: nextCanId(project) });
  const input = useRef<HTMLInputElement>(null), current = state.checkpoints.find(c => c.id === selected) || state.checkpoints[0];
  const changes = current ? compareProjects(current.project, project) : [];
  const validDraft = projectSchema.safeParse(project).success;
  const errors = validate(project).filter(i => i.level === 'error');
  return <div className="view-stack development-view"><div className="page-heading"><div><div className="eyebrow">DEVELOPMENT</div><h1>Keep building on what works.</h1><p>Save milestones, compare changes, and grow the same robot throughout the season.</p></div><button className="button primary" disabled={state.busy || !validDraft} onClick={() => { setAddition({ name: '', controller: 'none', can: nextCanId(project) }); setAdding(true); }}><Plus size={17} />Add a mechanism</button></div>
    <div className="iteration-flow"><span>Save a checkpoint</span><ArrowRight size={16} /><span>Add or refine</span><ArrowRight size={16} /><span>Review the changes</span><ArrowRight size={16} /><span>Build & test again</span></div>
    {state.error && <div className="issue error" role="alert"><p>{state.error}</p><button className="text-button" onClick={() => state.refresh()}>Retry storage</button></div>}
    {!validDraft && <div className="issue warning">Fix invalid field values before saving a checkpoint, importing, or restoring. Your last valid autosave is retained.</div>}
    <section className="panel checkpoint-create"><div><h2><Save size={20} />Save this design</h2><p>Name the milestone and record what changed or still needs testing. A checkpoint can include unfinished configuration work.</p><span className="tag">{errors.length ? `${errors.length} configuration ${errors.length === 1 ? 'issue' : 'issues'} in this draft` : 'Configuration checks pass · physical testing still required'}</span></div><div className="checkpoint-form"><label className="form-field"><span>Checkpoint name</span><input aria-label="Checkpoint name" maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="Drive base running · before adding intake" /></label><label className="form-field"><span>Development notes</span><textarea aria-label="Development notes" maxLength={1000} value={notes} onChange={e => setNotes(e.target.value)} placeholder="What changed? What was tested? What should the next programmer know?" /></label><button className="button primary" disabled={state.busy || !state.loaded || !validDraft || !name.trim() || state.checkpoints.length >= HISTORY_LIMIT} onClick={async () => { const id = await state.save(name, notes); if (id) { select(id); setName(''); setNotes(''); } }}><Save size={16} />{state.busy ? 'Saving…' : 'Save checkpoint'}</button></div></section>
    <div className="history-layout"><section className="panel history-list"><div className="panel-title"><div><h2><History size={20} />Checkpoint history</h2><p>{state.loaded ? `${state.checkpoints.length} / ${HISTORY_LIMIT} stored on this browser` : 'Loading checkpoints…'}</p></div></div><div className="history-transfer"><button className="button" disabled={!state.checkpoints.length || state.busy} onClick={() => download(historyFile(state.checkpoints), 'robotforge-development.json', 'application/json')}><Download size={15} />Download history</button><button className="button" disabled={state.busy} onClick={() => input.current?.click()}><Upload size={15} />Import history</button><input hidden ref={input} type="file" accept=".json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 20 * 1024 * 1024) throw Error('History backups must be under 20 MB.'); await state.importHistory(parseHistory(await file.text())); } catch (e) { toast.error(e instanceof Error ? e.message : 'Invalid history file.'); } e.target.value = ''; }} /></div>
      {!state.checkpoints.length && <p className="development-empty">Save your first checkpoint before the next design change. Imports, restores, and the mechanism shortcut also create recovery copies.</p>}
      <div className="checkpoint-options" role="group" aria-label="Saved checkpoints">{state.checkpoints.map(c => <button className={current?.id === c.id ? 'selected' : ''} key={c.id} aria-pressed={current?.id === c.id} onClick={() => select(c.id)}><b>{c.name}</b><span><Clock3 size={13} />{new Date(c.createdAt).toLocaleString()}</span><small>{c.project.name} · {c.project.language}{c.reason !== 'manual' ? ' · recovery copy' : ''}</small></button>)}</div>
    </section><section className="panel history-comparison"><div className="panel-title"><div><h2><GitCompareArrows size={20} />Changes since checkpoint</h2><p>{current ? `“${current.name}” → current working design` : 'Choose a saved milestone to compare.'}</p></div><span className="tag">{changes.length} items</span></div>{current && <><div className="checkpoint-notes"><b>Checkpoint notes</b><p>{current.notes || 'No notes were recorded.'}</p><small>{Object.values(current.project.checks).filter(Boolean).length} bench-check confirmations were recorded. A restore clears confirmations and keeps the captured library versions frozen.</small></div><ChangeList changes={changes} setTab={setTab} /><div className="checkpoint-actions"><button className="button" disabled={state.busy || !validDraft} onClick={() => setRestoring(current)}><RotateCcw size={15} />Restore this checkpoint</button><button className="button" onClick={() => download(JSON.stringify(restoreCheckpoint(current), null, 2), 'robotforge-checkpoint.json', 'application/json')}><Download size={15} />Project backup</button><button className="icon-button danger" aria-label="Delete selected checkpoint" disabled={state.busy} onClick={() => setRemoving(current)}><Trash2 size={16} /></button></div></>}</section></div>
    <section className="panel development-next"><h2>Extend the working design</h2><div>{[{ tab: 'Hardware', title: 'Add a component', text: 'Keep existing ports and IDs; add the new device to its subsystem.' }, { tab: 'Commands', title: 'Add a capability', text: 'Create another bounded action without changing current commands.' }, { tab: 'Logic builder', title: 'Refine behavior', text: 'Combine new and existing actions into reusable routines.' }, { tab: 'Code & export', title: 'Build the next revision', text: 'Every code change requires a fresh build before deployment.' }].map(item => <button key={item.tab} onClick={() => setTab(item.tab)}><b>{item.title}<ArrowRight size={16} /></b><span>{item.text}</span></button>)}</div></section>
    <div className="info-note"><LockKeyhole size={18} /><div>Checkpoints contain your configuration and dependency versions. They stay in this browser; download history for handoff or another computer. They do not archive compiled programs, firmware, or hand-edited source. Keep exported code and custom work in version control; regeneration creates a complete project and does not merge source edits.</div></div>
    <Dialog open={adding} onOpenChange={v => { if (!state.busy) setAdding(v); }}><DialogContent className="development-dialog"><DialogHeader><DialogTitle>Add a mechanism to this robot</DialogTitle><DialogDescription>Append a subsystem and optionally a motor with a starter action. Existing hardware, commands, routines, and buttons stay in place. A recovery checkpoint is saved first.</DialogDescription></DialogHeader><label className="form-field"><span>Mechanism name</span><input aria-label="New mechanism name" maxLength={32} value={addition.name} onChange={e => setAddition({ ...addition, name: e.target.value })} placeholder="Intake, climber, or feeder" /></label><label className="form-field"><span>Initial hardware</span><Select value={addition.controller} onValueChange={value => setAddition({ ...addition, controller: value as MechanismAddition['controller'] })}><SelectTrigger className="select-control" aria-label="Initial mechanism hardware"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Subsystem only · add hardware later</SelectItem>{['SparkMax', 'SparkFlex', 'TalonFX'].map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>{addition.controller !== 'none' && <><label className="form-field"><span>CAN ID on roboRIO CAN</span><input aria-label="New mechanism CAN ID" type="number" min={0} max={62} value={addition.can} onChange={e => setAddition({ ...addition, can: e.target.valueAsNumber })} /></label><p className="development-help">Adds a 30A current-limit setting and a “Run {addition.name || 'mechanism'}” action at 20% output for up to 1 second. Configure motor direction, limits, and ratings in Hardware. No button or autonomous assignment is added.</p></>}<DialogFooter><button className="button" disabled={state.busy} onClick={() => setAdding(false)}>Cancel</button><button className="button primary" disabled={state.busy || !addition.name.trim()} onClick={async () => { if (await state.addMechanism(addition)) { setAdding(false); setTab('Subsystems'); } }}>Add to working design</button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={!!restoring} onOpenChange={v => { if (!state.busy && !v) setRestoring(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restore “{restoring?.name}”?</AlertDialogTitle><AlertDialogDescription>The current working design will be saved as a recovery checkpoint first. This restores the selected configuration, freezes its library versions, and clears bench-check confirmations. It does not change the robot until you build and explicitly deploy.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={state.busy}>Keep working</AlertDialogCancel><AlertDialogAction disabled={state.busy} onClick={async e => { e.preventDefault(); if (restoring && await state.restore(restoring)) { select(restoring.id); setRestoring(null); } }}>Save current & restore</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={!!removing} onOpenChange={v => { if (!state.busy && !v) setRemoving(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete “{removing?.name}”?</AlertDialogTitle><AlertDialogDescription>This permanently removes this saved checkpoint from this browser. Download history first if you may need it later. Your current working design stays in place.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={state.busy}>Keep checkpoint</AlertDialogCancel><AlertDialogAction disabled={state.busy} onClick={async e => { e.preventDefault(); if (removing && await state.remove(removing.id)) setRemoving(null); }}>Delete checkpoint</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
