"use client";
import { useRef, useState, type PointerEvent } from 'react';
import { ArrowLeft, ArrowRight, Check, CircleAlert, CircuitBoard, Gauge, Grip, MousePointer2, Search, Settings2, X } from 'lucide-react';
import { toast } from 'sonner';
import { uid, type Project, type Issue } from '@/lib/robot-model';
import { driveType, driveLabel, corners } from '@/lib/drivetrain';
import { filterComponents } from '@/lib/component-catalog';
import { addDriveComponent, assignDriveComponent, assignedDriveKeys, compatibleDriveProfile, drivetrainUnits, existingDriveOptions, type DriveSlot, type DriveUnitId } from '@/lib/drivetrain-assembly';
import type { ComponentProfile } from '@/lib/component-layout';
import { productById } from '@/lib/hardware-catalog';
import MotorDetails from './motor-details';
import HardwareDevices from './hardware-devices';
import SubsystemDesigner from './subsystem-designer';
import { Hardware } from './studio-views';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from './ui/sheet';

function UnitIcon({kind}:{kind:string}){
  return <svg viewBox="0 0 80 72" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    {kind==='module'?<><circle cx="40" cy="34" r="27" strokeDasharray="3 5"/><circle cx="40" cy="34" r="18" fill="#e8eff5"/><rect x="31" y="15" width="18" height="39" rx="5" fill="#ed9a61"/><path d="M20 13l-5 10-5-8M24 62h32M40 56v6"/><circle cx="40" cy="34" r="4" fill="white"/></>:kind==='wheel'?<><rect x="22" y="9" width="36" height="51" rx="7" fill="#ed9a61"/>{[0,1,2,3].map(i=><path key={i} d={`M24 ${19+i*10}l29 -7`} stroke="white"/>)}<path d="M12 35h10M58 35h10"/></>:<><path d="M20 13h40v47H20z" fill="#e8eff5"/><path d="M40 9v55"/>{[15,31,47].map(y=><rect key={y} x="27" y={y} width="26" height="12" rx="3" fill="#ed9a61"/>)}</>}
  </g></svg>;
}
const slotNames:Record<DriveSlot,string>={drive:'Drive motor',steer:'Steering motor',encoder:'Encoder'};
type Props={project:Project;update:(patch:Partial<Project>)=>void;issues:Issue[];setTab:(tab:string)=>void};
type Drag={profile:ComponentProfile;pointer:number;x:number;y:number;moved:boolean};

export default function DrivetrainAssembly({project:p,update,issues,setTab}:Props){
  const units=drivetrainUnits(p),swerve=driveType(p)==='swerve',side=units[0].kind==='side';
  const [selectedUnit,setSelectedUnit]=useState<DriveUnitId>(units[0].id),[slot,setSlot]=useState<DriveSlot>('drive');
  const [search,setSearch]=useState(''),[armed,setArmed]=useState<ComponentProfile|null>(null),[dragging,setDragging]=useState(false),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState('');
  const tracking=useRef<Drag|null>(null),targets=useRef<Partial<Record<DriveSlot,HTMLButtonElement|null>>>({}),heading=useRef<HTMLHeadingElement>(null);
  const unit=units.find(u=>u.id===selectedUnit)||units[0],index=units.findIndex(u=>u.id===unit.id);
  const activeSlot=!swerve&&slot==='steer'?'drive':slot;
  const profiles=filterComponents(search).filter(c=>compatibleDriveProfile(p,c.id,activeSlot));
  const editingMotor=p.motors.find(m=>'motor:'+m.id===editing),editingDevice=p.devices?.find(d=>'device:'+d.id===editing);
  const editName=editingMotor?.name||editingDevice?.name;
  const hardwareIssues=issues.filter(i=>(i.area==='Hardware'||i.area==='Configuration')&&(!i.subsystems?.length||i.subsystems.includes('drive')));
  const unassigned=p.motors.filter(m=>m.subsystem==='drive'&&!assignedDriveKeys(p).has('motor:'+m.id));
  const run=(operation:()=>Partial<Project>)=>{try{update(operation());return true;}catch(e){toast.error(e instanceof Error?e.message:'Could not update drivetrain.');return false;}};
  function chooseUnit(id:DriveUnitId){setSelectedUnit(id);setArmed(null);setSlot('drive');setSearch('');setEditing(null);setMessage('');requestAnimationFrame(()=>heading.current?.focus({preventScroll:true}));}
  function place(profile:ComponentProfile,target:DriveSlot){if(run(()=>addDriveComponent(p,unit.id,target,profile.id,uid(profile.kind)))){setArmed(null);const text=slotNames[target]+' added to '+unit.label.toLowerCase()+'. Click it to set its connections.';setMessage(text);toast.success(text);}}
  function start(e:PointerEvent<HTMLButtonElement>,profile:ComponentProfile){if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);tracking.current={profile,pointer:e.pointerId,x:e.clientX,y:e.clientY,moved:false};}
  function move(e:PointerEvent<HTMLButtonElement>){const d=tracking.current;if(!d||d.pointer!==e.pointerId)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>6){d.moved=true;setDragging(true);}}
  function finish(e:PointerEvent<HTMLButtonElement>){const d=tracking.current;if(!d||d.pointer!==e.pointerId)return;tracking.current=null;setDragging(false);if(!d.moved){setArmed(d.profile);return;}const target=(Object.entries(targets.current) as [DriveSlot,HTMLButtonElement|null][]).find(([,el])=>{if(!el)return false;const r=el.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;});if(target)place(d.profile,target[0]);else{setMessage('Drop onto an empty motor or encoder slot in '+unit.label.toLowerCase()+'.');toast.info('Drop onto an empty component slot.');}}
  const cancel=()=>{tracking.current=null;setDragging(false);};
  function emptySlot(target:DriveSlot,optional=false){const options=existingDriveOptions(p,target),additional=side&&target==='drive'&&unit.motors.length>0;return <div className={'unit-slot '+(activeSlot===target?'active':'')} key={'empty-'+target}>
    <button ref={el=>{targets.current[target]=el;}} className={'unit-drop-slot '+(armed||dragging?'ready-to-drop':'')} aria-label={'Add '+(optional?'optional ':'')+slotNames[target].toLowerCase()+' to '+unit.label.toLowerCase()} onClick={()=>{if(armed)place(armed,target);else{setSlot(target);setSearch('');}}}>{target==='encoder'?<Gauge size={27}/>:<CircuitBoard size={27}/>}<b>{target==='encoder'&&swerve?'Absolute encoder':slotNames[target]}</b><small>{optional?'Optional · integrated feedback is used by default':additional?'Add another motor (optional)':'Required'}</small><span>{armed?'Place '+armed.name:'Drag here or choose from library'}</span></button>
    {!!options.length&&<select aria-label={'Use existing '+slotNames[target].toLowerCase()+' for '+unit.label.toLowerCase()} value="" onChange={e=>run(()=>assignDriveComponent(p,unit.id,target,e.target.value))}><option value="">Use existing hardware…</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>}
  </div>;}
  function occupiedSlot(target:DriveSlot,id:string,name:string,connection:string){const key=(target==='encoder'?'device:':'motor:')+id;return <div className="unit-slot filled" key={id}><button className="unit-component" aria-label={'Configure '+name} onClick={()=>setEditing(key)}>{target==='encoder'?<Gauge size={29}/>:<CircuitBoard size={29}/>}<small>{target==='encoder'&&swerve?'Absolute encoder':slotNames[target]}</small><b>{name}</b><span>{connection}</span><em><Settings2 size={13}/>Configure</em></button>{(!side||target==='encoder')&&<button className="unit-unassign" onClick={()=>run(()=>assignDriveComponent(p,unit.id,target,''))}>Unassign {slotNames[target].toLowerCase()}</button>}</div>;}
  return <div className="view-stack drive-assembly">
    <section className="panel drive-unit-overview" aria-label="Drivetrain units"><div className="panel-title"><div><h2>Assemble your {driveLabel(p).toLowerCase()} drivetrain</h2><p>{swerve?'Four modules. Each needs a drive motor, a steering motor, and an absolute encoder.':side?'Two sides. Add one or more drive motors to each side, plus an optional distance encoder.':'Four wheels. Each needs a drive motor; you can also add an external distance encoder.'}</p></div><span className="tag">{units.filter(u=>u.complete).length} / {units.length} {side?'sides':swerve?'modules':'wheels'} assembled</span></div>
      <div className={'drive-unit-map '+(side?'two-sides':'four-corners')}><span className="unit-front">↑ FRONT OF ROBOT</span>{units.map(u=><button key={u.id} className={'drive-unit '+(u.id===unit.id?'selected ':'')+(u.complete?'assembled':'')} aria-label={'Assemble '+u.label.toLowerCase()+(side?'':swerve?' module':' wheel')} aria-pressed={u.id===unit.id} onClick={()=>chooseUnit(u.id)}><UnitIcon kind={u.kind}/><div><b>{u.label}{swerve?' module':!side?' wheel':''}</b><small>{side?`${u.motors.length} drive motor${u.motors.length===1?'':'s'}`:`${u.motors.length?'Drive ✓':'Drive needed'}${swerve?u.steer?' · Steer ✓':' · Steer needed':''}`}</small><small>{u.encoder?'Encoder assigned':swerve?'Encoder needed':'Integrated motor feedback'}</small></div><span className="unit-completion">{u.complete?<Check size={17}/>:u.missing.length}</span></button>)}</div>
    </section>
    <section className="drive-unit-builder" aria-label={unit.label+' component assembly'}><div className="designer-heading"><div><div className="eyebrow">{side?'SIDE':swerve?'MODULE':'WHEEL'} {index+1} OF {units.length}</div><h2 ref={heading} tabIndex={-1}>{unit.label}{swerve?' module':!side?' wheel':''}</h2><p>{side?'Add 1–4 motors, using matching counts on both sides.':swerve?'Build this module, then repeat for the next corner.':'Add the controller that drives this wheel.'} Click a placed component to configure it.</p></div><UnitIcon kind={unit.kind}/></div>
      <div className="drive-unit-workspace"><aside className="component-tray" aria-label="Drivetrain component library"><h3>Choose a component</h3><div className="drive-slot-tabs">{(['drive',...(swerve?['steer']:[]),'encoder'] as DriveSlot[]).map(s=><button key={s} aria-pressed={activeSlot===s} onClick={()=>{setSlot(s);setSearch('');setArmed(null);}}>{s==='drive'?'Drive':s==='steer'?'Steer':'Encoders'}</button>)}</div><label className="catalog-search"><Search size={16}/><input aria-label="Search drivetrain components" placeholder="Find a controller or encoder…" value={search} onChange={e=>setSearch(e.target.value)}/></label><small>{profiles.length} compatible profiles · Drag or select</small><div className="component-tray-list">{profiles.map(c=><button key={c.id} className={'component-template '+(armed?.id===c.id?'selected':'')} title={c.description} aria-label={'Place '+c.name} aria-pressed={armed?.id===c.id} onPointerDown={e=>start(e,c)} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel} onClick={e=>{if(e.detail===0)setArmed(c);}}>{c.kind==='motor'?<CircuitBoard/>:<Gauge/>}<span><b>{c.name}</b><small>{c.brand} · {c.connection}</small></span><Grip size={14}/></button>)}{!profiles.length&&<p className="component-help">No matches. Try another component name.</p>}</div><p className="component-help">The motor model is set inside its controller. Only supported feedback options appear here.</p></aside>
      <div className="unit-assembly-board">{armed&&<div className="placement-prompt" role="status"><MousePointer2 size={16}/><span>Select a slot for {armed.name}.</span><button aria-label="Cancel drivetrain placement" onClick={()=>setArmed(null)}><X size={16}/></button></div>}<div className={'unit-component-slots '+(side?'side-slots':'')}>
        {unit.motors.map(m=>occupiedSlot('drive',m.id,m.name,`${m.type} · ${m.type.startsWith('PWM')?'PWM':'CAN'} ${m.can}`))}
        {(side?unit.motors.length<4:!unit.motors.length)&&emptySlot('drive')}
        {swerve&&(unit.steer?occupiedSlot('steer',unit.steer.id,unit.steer.name,`${unit.steer.type} · CAN ${unit.steer.can}`):emptySlot('steer'))}
        {unit.encoder?occupiedSlot('encoder',unit.encoder.id,unit.encoder.name,productById(unit.encoder.product)?.connection==='CAN'?`CAN ${unit.encoder.address}`:`DIO ${unit.encoder.channel}${!swerve?' / '+unit.encoder.channelB:''}`):emptySlot('encoder',!swerve)}
      </div>{swerve&&unit.encoder&&<label className="form-field unit-offset"><span>{unit.label} forward offset (rotations)</span><input aria-label={unit.label+' forward offset (rotations)'} type="number" min={-1} max={1} step={.001} value={Number.isFinite(unit.offset)?unit.offset:''} onChange={e=>update({drive:{...p.drive,modules:corners.map(c=>{const old=p.drive.modules?.find(m=>m.corner===c)||{corner:c,driveMotor:'',steerMotor:'',encoder:'',offset:0};return c===unit.id?{...old,offset:e.target.valueAsNumber}:old;})}})}/><small>Point this wheel forward and enter its calibrated absolute encoder reading. One module rotation must equal one encoder rotation.</small></label>}
      {!swerve&&unit.encoder&&<p className="unit-feedback-note">This encoder supplies distance and speed for {unit.label.toLowerCase()} odometry. Open it and set <b>meters travelled per full encoder pulse</b>; verify its direction before driving.</p>}
      {!unit.complete&&<p className="unit-feedback-note">Still needed: {unit.missing.join(', ')}.</p>}
      <p className="unit-feedback-note">Connections and roles are assigned to this {unit.kind} automatically. Match suggested CAN IDs and channels to your physical hardware.</p></div></div>
      <div className="unit-navigation"><button className="button" disabled={index===0} onClick={()=>chooseUnit(units[index-1].id)}><ArrowLeft size={15}/>Previous {unit.kind}</button><span>{unit.complete?'Hardware assigned':unit.missing.length+' required parts remaining'}</span><button className="button primary" disabled={index===units.length-1} onClick={()=>chooseUnit(units[index+1].id)}>{index<units.length-1?'Next: '+units[index+1].label:'Last '+unit.kind}<ArrowRight size={15}/></button></div><div className="sr-only" aria-live="polite">{message}</div>
    </section>
    {!!unassigned.length&&<div className="wizard-callout"><CircleAlert size={20}/><div><b>{unassigned.length} drivetrain motor{unassigned.length===1?' needs':'s need'} a unit assignment.</b><p>Choose “Use existing hardware” in an empty slot. Your existing motors and settings are preserved.</p></div></div>}
    <details className="assembly-details"><summary>Chassis measurements, tuning & heading sensor</summary><Hardware project={p} update={update} issues={issues} setTab={setTab} tab="Build wizard" subsystemId="drive" hardwareStage="feedback" driveAssembly/></details>
    <details className="assembly-details"><summary>Other drivetrain hardware & unassigned components</summary><SubsystemDesigner project={p} update={update} subsystemId="drive" issues={issues} setTab={setTab} hideDriveSetup excludeKeys={[...assignedDriveKeys(p)]} title="Other drivetrain hardware"/></details>
    {!!hardwareIssues.length&&<details className="assembly-details"><summary><CircleAlert size={17}/>{hardwareIssues.length} drivetrain checks to review</summary><div className="assembly-findings">{hardwareIssues.map((i,n)=><p key={n}>{i.message}</p>)}</div></details>}
    <Sheet open={!!editName} onOpenChange={open=>{if(!open)setEditing(null);}}><SheetContent className="component-inspector"><SheetHeader><SheetTitle>{editName||'Component settings'}</SheetTitle><SheetDescription>{unit.label}{side?'':' '+unit.kind} · Changes save with the drivetrain.</SheetDescription></SheetHeader>{editName&&<div className="component-inspector-content">{editingMotor?<><MotorDetails project={p} update={update} motor={editingMotor}/>{side&&<button className="button unit-move-side" onClick={()=>{if(run(()=>assignDriveComponent(p,unit.id==='left'?'right':'left','drive',editingMotor.id)))setEditing(null);}}>Move to {unit.id==='left'?'right':'left'} side</button>}</>:editingDevice&&<HardwareDevices key={editingDevice.id} project={p} update={update} mode="devices" hideLibrary selectedDeviceId={editingDevice.id} subsystemId="drive" onAddMotor={()=>{}} motorEditor={()=>null}/>}<button className="button primary component-done" onClick={()=>setEditing(null)}>Done</button></div>}</SheetContent></Sheet>
  </div>;
}
