"use client";
import type { Project } from '@/lib/robot-model';
import { corners,cornerNames,driveTypes,driveType,isHolonomic,controlStyle,selectDrivetrain,type DriveType } from '@/lib/drivetrain';
import { productById } from '@/lib/hardware-catalog';

type Props={project:Project;update:(patch:Partial<Project>)=>void};
function NumberField({label,value,onChange,min,max,step=.01}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number}){return <label className="form-field"><span>{label}</span><input aria-label={label} type="number" value={Number.isFinite(value)?value:''} min={min} max={max} step={step} onChange={e=>onChange(e.target.valueAsNumber)}/></label>;}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label className="form-field"><span>{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
export function DrivetrainEditor({project:p,update,layoutOnly=false}:Props & {layoutOnly?:boolean}){
 const type=driveType(p),holo=isHolonomic(p),motors=p.motors.filter(m=>m.subsystem==='drive');
 const options=(role:string)=>[{value:'',label:'Choose a motor…'},...motors.filter(m=>m.role===role).map(m=>({value:m.id,label:`${m.name} · ${m.type} · ${m.can}`}))];
 const encoders=[{value:'',label:'Choose an absolute encoder…'},...(p.devices||[]).filter(d=>d.subsystem==='drive'&&['cancoder','duty'].includes(productById(d.product)?.adapter||'')).map(d=>({value:d.id,label:d.name}))];
 const set=(patch:Partial<Project['drive']>)=>update({drive:{...p.drive,...patch}});
 return <section className="panel drivetrain-panel"><div className="panel-title"><div><h2>Drivetrain layout</h2><p>Choose the chassis, then match its hardware. Changing layouts preserves your components and commands.</p></div></div>
  <div className="drivetrain-types">{driveTypes.map(t=><button key={t.value} className={'drive-type '+(type===t.value?'selected':'')} aria-pressed={type===t.value} onClick={()=>{if(t.value!==type)update(selectDrivetrain(p,t.value as DriveType));}}><b>{t.label}</b><small>{t.description}</small></button>)}</div>
  <div className="drive-layout-summary"><svg viewBox="0 0 260 190" role="img" aria-label={`${driveTypes.find(t=>t.value===type)?.label} layout, front at top`}><rect x="55" y="35" width="150" height="120" rx="12" fill="#eaf0f6" stroke="#7890a8"/><path d="M130 50V12m-6 8 6-8 6 8" fill="none" stroke="#172b45" strokeWidth="2"/>{corners.map((c,i)=>{const x=i%2===0?40:195,y=i<2?37:123;return <g key={c}><rect x={x} y={y} width="25" height="33" rx={type==='swerve'?12:4} fill="#ec8848"/>{type==='mecanum'&&<path d={(i===0||i===3)?`M${x+3} ${y+6}l19 19M${x+3} ${y+16}l10 10`:`M${x+3} ${y+25}l19-19M${x+3} ${y+15}l10-10`} stroke="white" strokeWidth="2"/>}<text x={i%2===0?30:230} y={y+22} textAnchor="middle" fontSize="10" fill="#263a51">{['FL','FR','BL','BR'][i]}</text></g>;})}</svg><div><b>{holo?'Forward + strafe + rotation':'Left and right wheel groups'}</b><p>{type==='swerve'?'Assign four drive motors, four steering motors, and four absolute encoders. Zero means each wheel points forward; positive steering is counterclockwise.':type==='mecanum'?'Assign one motor to each corner. Viewed from above, the rollers form an X. Verify all four encoder signs and motor directions.':'Assign each motor to the left or right side below. Supports 1–4 motors per side, with equal counts. Choose arcade or tank controls on the Controls page.'}</p></div></div>
  {holo&&!layoutOnly&&<><div className="form-grid"><NumberField label="Wheelbase — front to rear (m)" value={p.drive.wheelbase??.6} min={.2} max={2} onChange={wheelbase=>set({wheelbase})}/><NumberField label="Maximum rotation (rad/s)" value={p.drive.maxAngularSpeed??4} min={.1} max={15} onChange={maxAngularSpeed=>set({maxAngularSpeed})}/><NumberField label="Path translation kP" value={p.drive.translationKP??3} min={.1} max={20} onChange={translationKP=>set({translationKP})}/><NumberField label="Path rotation kP" value={p.drive.rotationKP??3} min={.1} max={20} onChange={rotationKP=>set({rotationKP})}/>{type==='swerve'&&<NumberField label="Steering kP (V/rad)" value={p.drive.steerKP??4} min={.1} max={30} onChange={steerKP=>set({steerKP})}/>}</div>
  <div className="module-grid">{corners.map((corner,i)=>{const module=p.drive.modules?.find(m=>m.corner===corner)||{corner,driveMotor:'',steerMotor:'',encoder:'',offset:0};const edit=(patch:Partial<typeof module>)=>set({modules:corners.map(c=>c===corner?{...module,...patch}:p.drive.modules?.find(m=>m.corner===c)||{corner:c,driveMotor:'',steerMotor:'',encoder:'',offset:0})});return <div className="module-editor" key={corner}><h3>{cornerNames[i]}</h3><Choice label={cornerNames[i]+' drive motor'} value={type==='swerve'?module.driveMotor:p.drive.wheels?.[corner]||''} options={options('wheel')} onChange={id=>type==='swerve'?edit({driveMotor:id}):set({wheels:{frontLeft:'',frontRight:'',backLeft:'',backRight:'',...p.drive.wheels,[corner]:id}})}/>{type==='swerve'&&<><Choice label={cornerNames[i]+' steering motor'} value={module.steerMotor} options={options('steer')} onChange={steerMotor=>edit({steerMotor})}/><Choice label={cornerNames[i]+' absolute encoder'} value={module.encoder} options={encoders} onChange={encoder=>edit({encoder})}/><NumberField label={cornerNames[i]+' forward offset (rotations)'} value={module.offset} min={-1} max={1} step={.001} onChange={offset=>edit({offset})}/></>}</div>;})}</div><div className="panel-foot">{type==='swerve'?'Add components in the Motors and Sensors steps, or the Hardware library, and assign them to Drivetrain. Steering feedback supports CANcoder and absolute duty-cycle encoders wired to roboRIO DIO. Read the encoder with the wheel pointing forward and enter that value as its offset.':'Autonomous uses a WPILib mecanum trajectory follower. The route uses the entered field coordinates on both alliances; verify your starting pose and route for the current alliance.'}</div></>}
 </section>;
}
export function DriveControls({project:p,update}:Props){
 const c=p.controls,set=(patch:Partial<Project['controls']>)=>update({controls:{...c,...patch}}),style=controlStyle(p);
 const axes=style==='tank'?[['forward','Left stick axis',c.forwardAxis,c.forwardSign],['right','Right stick axis',c.rightAxis??5,c.rightSign??-1]]:style==='holonomic'?[['forward','Forward axis',c.forwardAxis,c.forwardSign],['strafe','Strafe axis',c.strafeAxis??0,c.strafeSign??-1],['turn','Turn axis',c.turnAxis,c.turnSign]]:[['forward','Forward axis',c.forwardAxis,c.forwardSign],['turn','Turn axis',c.turnAxis,c.turnSign]];
 return <section className="panel"><div className="panel-title"><div><h2>Drive controls</h2><p>{style==='holonomic'?'Forward and strafe on the left stick; rotate on the right stick.':style==='tank'?'Each stick commands one side of the drivetrain.':'One forward axis and one turn axis.'} Axis numbers refer to the driver controller.</p></div></div><div className="form-grid">{!isHolonomic(p)&&<Choice label="Driving style" value={style} onChange={driveStyle=>set({driveStyle:driveStyle as 'arcade'|'tank'})} options={[{value:'arcade',label:'Arcade — forward + turn'},{value:'tank',label:'Tank — left + right'}]}/>} {axes.map(([key,label,axis,sign])=><div key={key}><NumberField label={String(label)} value={Number(axis)} min={0} max={11} step={1} onChange={v=>set({[key+'Axis']:v})}/><Choice label={label+' direction'} value={String(sign)} onChange={v=>set({[key+'Sign']:Number(v)})} options={[{value:'-1',label:'Inverted (−1)'},{value:'1',label:'Normal (+1)'}]}/></div>)}<NumberField label="Joystick deadband" value={c.deadband} min={0} max={.3} onChange={deadband=>set({deadband})}/><NumberField label="Drive output cap" value={c.maxOutput} min={.05} max={1} step={.05} onChange={maxOutput=>set({maxOutput})}/>{isHolonomic(p)&&<Choice label="Driving reference" value={c.fieldRelative?'field':'robot'} onChange={v=>set({fieldRelative:v==='field'})} options={[{value:'robot',label:'Robot relative'},{value:'field',label:'Field relative — blue field axes'}]}/>}</div><div className="panel-foot">Start with a low output cap. For field-relative driving, verify the robot heading against the field before enabling.</div></section>;
}
