"use client";
import CanIdInput from './can-id-input';
import { canAddressLabel } from '@/lib/can-address';
import { useState, type ReactNode } from 'react';
import { Plus,Search,Trash2,ArrowUpRight,Cable,Check,BookOpen } from 'lucide-react';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from '@/components/ui/accordion';
import { Switch } from '@/components/ui/switch';
import { productById,isActuator,isSensor,type Device } from '@/lib/hardware-catalog';
import { componentCatalog,componentBrands,componentCategories,filterComponents } from '@/lib/component-catalog';
import { activeTractionEncoders } from '@/lib/drivetrain';
import { newProjectDevice } from '@/lib/component-layout';
import { motorCatalog } from '@/lib/motor-catalog';
import { uid,type Motor,type Project } from '@/lib/robot-model';
import { toast } from 'sonner';
type Props={hideLibrary?:boolean;selectedDeviceId?:string;mode?:'all'|'motors'|'devices';subsystemId?:string;project:Project;update:(patch:Partial<Project>)=>void;onAddMotor:(type:Motor['type'])=>void;motorEditor:(browseMotors:()=>void)=>ReactNode};
function Pick({label,value,values,onChange}:{label:string;value:string;values:{value:string;label:string}[];onChange:(v:string)=>void}){return <label className="form-field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="select-control"><SelectValue/></SelectTrigger><SelectContent>{values.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;}
export const busOptions=(p:Project)=>[{value:'rio',label:'roboRIO CAN'},...(p.devices||[]).filter(d=>productById(d.product)?.adapter==='canbus').map(d=>({value:d.bus,label:d.bus+' · CANivore'}))];
export default function HardwareDevices({project:p,update,onAddMotor,motorEditor,subsystemId,mode='all',hideLibrary=false,selectedDeviceId}:Props){
 const [search,setSearch]=useState(''),[brand,setBrand]=useState('all'),[category,setCategory]=useState('all'),[open,setOpen]=useState(selectedDeviceId||'');const ds=p.devices||[];const visibleDevices=ds.filter(d=>(!subsystemId||d.subsystem===subsystemId)&&(!selectedDeviceId||d.id===selectedDeviceId));
 const inMode=(c:typeof componentCatalog[number])=>mode==='all'||(mode==='motors'?c.kind==='motor':c.kind!=='motor');
 const filtered=filterComponents(search,brand,category).filter(inMode);
 function browseMotors(){setSearch('');setBrand('all');setCategory('Motor controllers');document.getElementById('component-library')?.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('component-search')?.focus({preventScroll:true});}

 const change=(id:string,patch:Partial<Device>)=>update({devices:ds.map(d=>d.id===id?{...d,...patch}:d)});
 function add(product:string){try{const d=newProjectDevice(p,product,uid('device'),subsystemId||p.subsystems.find(s=>s.id!=='drive')?.id||'drive');update({devices:[...ds,d]});setOpen(d.id);toast.success(d.name+' added. Configure its connections below.');}catch(e){toast.error(e instanceof Error?e.message:'Could not add component.');}}
 return <>{!hideLibrary&&<section id="component-library" className="panel component-library"><div className="panel-title"><div><h2>{mode==='motors'?'Choose motor controllers':mode==='devices'?'Choose sensors & components':'Component library'}</h2><p>{mode==='motors'?'Choose a controller, then configure its address, direction, and limits below.':mode==='devices'?'Add feedback, power, and accessories for this subsystem. Each profile shows its code support.':'Motor controllers, sensors, power, and accessories — add the hardware on your robot.'}</p></div><span className="tag">{componentCatalog.filter(inMode).length} component profiles</span></div>
 {mode==='all'&&<div className="catalog-shortcuts"><button type="button" className="button" aria-pressed={category==='Motor controllers'} onClick={browseMotors}>Motor controllers <span>{motorCatalog.length}</span></button><a className="button" href="#motor-controllers">Configure your motors <span>{p.motors.filter(m=>!subsystemId||m.subsystem===subsystemId).length}</span></a>{category!=='all'&&<button type="button" className="text-button" onClick={()=>{setCategory('all');setBrand('all');setSearch('');}}>All components</button>}</div>}
 <div className="catalog-filters"><label className="catalog-search"><Search size={18}/><input id="component-search" aria-label="Search components" placeholder={mode==='devices'?'Search CANcoder, CANrange, limit switch…':'Search SPARK MAX, Talon, CANrange…'} value={search} onChange={e=>setSearch(e.target.value)}/></label><Pick label="Manufacturer" value={brand} onChange={setBrand} values={[{value:'all',label:'All manufacturers'},...componentBrands.map(value=>({value,label:value}))]}/>{mode!=='motors'&&<Pick label="Category" value={category} onChange={setCategory} values={[{value:'all',label:'All components'},...componentCategories.filter(c=>mode!=='devices'||c!=='Motor controllers').map(value=>({value,label:value}))]}/>}</div>
 <div className="catalog-results" aria-live="polite">{filtered.length} matching profiles</div>
 <div className="catalog-grid">{filtered.map(d=>{const motor=d.kind==='motor';const unavailable=motor&&d.javaOnly&&p.language!=='Java';return <article className="catalog-card" key={d.id}><div className="catalog-card-top"><small>{d.brand}</small><span className={'support-tag '+(motor?'motor':d.adapter)}>{motor?(d.javaOnly?'Java only':'Java · C++ · Python'):d.adapter==='passive'?'Wiring / inventory':d.adapter==='custom'?'Integration needed':'Code adapter'}</span></div><h3>{d.name}</h3><span className="connection-label">{d.category} · {d.connection}</span><p>{d.description}</p>{unavailable&&<small className="catalog-unavailable">Switch the project language to Java to add this controller.</small>}<div><a href={d.docs} target="_blank" rel="noreferrer">Setup guide <ArrowUpRight size={13}/></a><button className="button" aria-label={'Add '+d.name} onClick={()=>motor?onAddMotor(d.type):add(d.id)} disabled={!!unavailable||(motor?p.motors.length>=40:ds.length>=80)}><Plus size={15}/>Add</button></div></article>;})}</div>
 {!filtered.length&&<div className="empty-state"><Search/><h3>No matching components</h3><p>Try a controller name such as SPARK MAX or Talon, a manufacturer, or an interface such as CAN or PWM.</p><button className="button" onClick={()=>{setSearch('');setBrand('all');setCategory('all');}}>Clear filters</button></div>}</section>}
 {mode!=='devices'&&motorEditor(browseMotors)}
 {mode!=='motors'&&<section className="panel configured-devices"><div className="panel-title"><div><h2>Your sensors, power & accessories</h2><p>{visibleDevices.length} configured · Required vendor libraries are included automatically.</p></div><Cable size={22}/></div>{!visibleDevices.length?<div className="device-empty"><BookOpen size={25}/><p>Add a component above to configure its ports, calibration, and subsystem.</p></div>:<Accordion type="single" collapsible value={open} onValueChange={setOpen}>{visibleDevices.map(d=>{const def=productById(d.product);if(!def)return null;const a=def.adapter,passive=a==='passive',custom=a==='custom',valve=['solenoidRev','solenoidCtre','doubleRev','doubleCtre'].includes(a);const number=(key:keyof Device,label:string,min:number,max:number,step=1)=><label className="form-field" key={key}><span>{label}</span><input type="number" aria-label={`${label} ${d.name}`} min={min} max={max} step={step} value={Number.isFinite(d[key])?String(d[key]):''} onChange={e=>change(d.id,{[key]:e.target.valueAsNumber})}/></label>;return <AccordionItem value={d.id} key={d.id}><AccordionTrigger><span className="device-accordion-title"><b>{d.name}</b><small>{def.brand} · {def.connection==='CAN'?`${d.bus} · ${canAddressLabel(d.address)}`:def.connection}</small></span><span className="support-tag">{custom?'Integration needed':passive?'Wiring only':isActuator(a)?'Command output':isSensor(a)?'Sensor feedback':'Infrastructure'}</span></AccordionTrigger><AccordionContent><div className="device-details"><p className={custom?'device-integration-needed':'device-guidance'}>{def.description}</p><div className="form-grid"><label className="form-field"><span>Device name</span><input aria-label={'Device name '+d.name} value={d.name} onChange={e=>change(d.id,{name:e.target.value})}/></label><Pick label={'Subsystem '+d.name} value={d.subsystem} values={p.subsystems.map(s=>({value:s.id,label:s.name}))} onChange={subsystem=>change(d.id,{subsystem})}/>
 {def.connection==='CAN'&&<><label className="form-field"><span>CAN ID</span><CanIdInput label={'CAN ID '+d.name} value={d.address} onChange={address=>change(d.id,{address})}/><small>Enter the ID configured on this device (0–62).</small></label><Pick label={'CAN bus '+d.name} value={d.bus} values={['cancoder','canrange','candi','candle','pigeon'].includes(a)?busOptions(p):[{value:'rio',label:'roboRIO CAN'}]} onChange={bus=>change(d.id,{bus})}/></>}
 {a==='canbus'&&<label className="form-field"><span>CANivore name / serial</span><input aria-label={'CANivore name '+d.name} value={d.bus} onChange={e=>change(d.id,{bus:e.target.value})}/><small>Match the name in Phoenix Tuner. Use letters, numbers, underscores or hyphens.</small></label>}
 {['digital','digitalOut','duty','quadrature','ultrasonic','analog','analogEncoder','servo','blinkin','servoHub'].includes(a)&&number('channel',a==='servoHub'?'Servo Hub channel':def.connection==='Analog'?'Analog channel':def.connection==='PWM'?'PWM channel':a==='ultrasonic'?'Ping DIO channel':'DIO channel',0,a==='servoHub'?5:def.connection==='Analog'?7:def.connection==='PWM'?19:25)}
 {['quadrature','ultrasonic'].includes(a)&&number('channelB',a==='ultrasonic'?'Echo DIO channel':'Encoder B DIO channel',0,25)}
 {valve&&<><Pick label={'Pneumatic module '+d.name} value={d.module||'unassigned'} values={[{value:'unassigned',label:'Select a module'},...ds.filter(h=>productById(h.product)?.adapter===(a.endsWith('Rev')?'ph':'pcm')).map(h=>({value:h.id,label:h.name+` · ${canAddressLabel(h.address)}`}))]} onChange={v=>change(d.id,{module:v==='unassigned'?'':v})}/>{number('channel','Forward / single channel',0,a.endsWith('Rev')?15:7)}{a.startsWith('double')&&number('channelB','Reverse channel',0,a.endsWith('Rev')?15:7)}</>}
 {['duty','quadrature','analog','analogEncoder','cancoder','canrange','pigeon','navx','tof','encoderLegacy','pigeonLegacy'].includes(a)&&<>{number('scale',a==='quadrature'?(activeTractionEncoders(p).some(e=>e.id===d.id)?'Distance per pulse (m)':'Distance per full encoder pulse'):'Scale',.0000001,10000,.001)}{number('offset','Zero offset',-10000,10000,.001)}</>}
 {['digital','duty','quadrature','analog','analogEncoder','cancoder'].includes(a)&&<label className="switch-label"><Switch aria-label={'Invert sensor '+d.name} checked={d.inverted} onCheckedChange={inverted=>change(d.id,{inverted})}/>{a==='digital'?'Active-high input':'Reverse sensor direction'}</label>}
 {['color','navx'].includes(a)&&<Pick label={'Connection '+d.name} value={d.interface} values={a==='color'?[{value:'onboard',label:'roboRIO onboard I2C'},{value:'mxp',label:'MXP I2C'}]:[{value:'mxp',label:'MXP SPI'},{value:'onboard',label:'I2C'},{value:'usb1',label:'USB 1'},{value:'usb2',label:'USB 2'}]} onChange={v=>change(d.id,{interface:v as Device['interface']})}/>}
 {['ph','pcm'].includes(a)&&<label className="switch-label"><Switch aria-label={'Enable compressor '+d.name} checked={d.compressor} onCheckedChange={compressor=>change(d.id,{compressor})}/>Enable compressor with pressure switch while robot enabled</label>}
 {a==='limelight'&&<label className="form-field"><span>NetworkTables camera name</span><input aria-label={'Camera name '+d.name} value={d.table} onChange={e=>change(d.id,{table:e.target.value})}/><small>Match the camera hostname, e.g. limelight-front.</small></label>}
 {a==='candle'&&<>{number('count','LED count including 8 onboard',1,400)}{number('red','Red',0,255)}{number('green','Green',0,255)}{number('blue','Blue',0,255)}</>}
 {['servo','servoHub'].includes(a)&&<>{number('pulseMin','Minimum pulse (µs)',500,2500)}{number('pulseMax','Maximum pulse (µs)',500,2500)}</>}
 </div><label className="form-field"><span>Wiring / commissioning notes</span><textarea aria-label={'Notes '+d.name} value={d.notes} onChange={e=>change(d.id,{notes:e.target.value})} placeholder="Connector, power source, calibration, mounting…"/></label><div className="device-detail-footer"><a href={def.docs} target="_blank" rel="noreferrer">Manufacturer setup guide <ArrowUpRight size={14}/></a><button className="button danger" onClick={()=>{if(p.commands.some(c=>c.device===d.id||c.untilDevice===d.id)||ds.some(x=>x.module===d.id)||a==='canbus'&&(p.motors.some(m=>m.bus===d.bus)||ds.some(x=>x.id!==d.id&&x.bus===d.bus)||p.drive.gyroBus===d.bus)){toast.error('Remove this component’s command or connection assignments first.');return;}update({devices:ds.filter(x=>x.id!==d.id)});}}><Trash2 size={15}/>Remove component</button></div>{!passive&&!custom&&<div className="device-generated"><Check size={15}/>Included in generated source and HARDWARE.md</div>}</div></AccordionContent></AccordionItem>;})}</Accordion>}</section>}</>;
}
