"use client";
import { useRef, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowRight, Blocks, Clock3, Copy, GitFork, Plus, RotateCcw, Trash2, Zap } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { toast } from 'sonner';
import { uid, type Project, type Issue } from '@/lib/robot-model';
import { routineSource, routineDuration, routineRequirements, stepCommands, stepLabels, stepHelp, type Routine, type RoutineStep } from '@/lib/routines';

type Props = { project: Project; update: (p: Partial<Project>) => void; setTab: (s: string) => void; issues: Issue[] };
function Pick({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (v: string) => void }) {
  return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="select-control"><SelectValue placeholder="Choose an action" /></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
export default function LogicBuilder({ project: p, update, setTab, issues }: Props) {
  const routines = p.routines || [];
  const [selected, select] = useState(routines[0]?.id || '');
  const [language, setLanguage] = useState<Project['language']>(p.language);
  const [dragged, setDragged] = useState<string | null>(null);
  const undo = useRef<Routine[][]>([]);
  const [canUndo, setCanUndo] = useState(false);
  const current = routines.find(r => r.id === selected) || routines[0];
  const choices = p.commands.map(c => ({ value: c.id, label: c.name + ' · ' + (p.subsystems.find(s => s.id === c.subsystem)?.name || 'Missing subsystem') }));
  const independent = p.commands.filter((c, i, all) => all.findIndex(x => x.subsystem === c.subsystem) === i).slice(0, 2);
  function save(next: Routine[]) { undo.current.push(structuredClone(routines)); if (undo.current.length > 30) undo.current.shift(); setCanUndo(true); update({ routines: next }); }
  function patch(change: Partial<Routine>) { if (current) save(routines.map(r => r.id === current.id ? { ...r, ...change } : r)); }
  function addRoutine(template = false) {
    const r: Routine = { id: uid('routine'), name: template ? 'Two-action sequence' : 'New routine', timeout: 15, steps: [] };
    if (template && p.commands.length >= 2) r.steps = [{ id: uid('block'), type: 'action', command: p.commands[0].id }, { id: uid('block'), type: 'wait', seconds: .5 }, { id: uid('block'), type: 'action', command: p.commands[1].id }];
    save([...routines, r]); select(r.id);
  }
  function addStep(type: RoutineStep['type']) {
    if (!current) return;
    const id = uid('block');
    const step: RoutineStep = type === 'wait' ? { id, type, seconds: .5 } : type === 'action' ? { id, type, command: p.commands[0].id } : { id, type, commands: independent.map(c => c.id) };
    patch({ steps: [...current.steps, step] });
  }
  function replaceStep(id: string, next: RoutineStep) { if (current) patch({ steps: current.steps.map(s => s.id === id ? next : s) }); }
  function move(from: number, to: number) {
    if (!current || from < 0 || to < 0 || from >= current.steps.length || to >= current.steps.length || from === to) return;
    const steps = [...current.steps]; const [step] = steps.splice(from, 1); steps.splice(to, 0, step); patch({ steps });
  }
  const findings = issues.filter(i => i.area === 'Logic builder' || i.area === 'Configuration' && i.message.startsWith('routines'));
  return <div className="view-stack logic-view">
    <div className="logic-intro"><div><h2>Build behavior from actions</h2><p>Arrange blocks, see the code, then assign the routine to a button or autonomous step.</p></div><button className="button" onClick={() => setTab('Commands')}>Edit individual actions <ArrowRight size={16} /></button></div>
    <section className="panel routine-toolbar"><div className="routine-picker"><label>Routine</label><Pick label="Selected routine" value={current?.id || ''} options={routines.map(r => ({ value: r.id, label: r.name }))} onChange={select} /></div><button className="button primary" disabled={routines.length >= 20} onClick={() => addRoutine()}><Plus size={16} />New routine</button><button className="button" disabled={!canUndo} onClick={() => { const previous = undo.current.pop(); if (previous) update({ routines: previous }); setCanUndo(undo.current.length > 0); }}><RotateCcw size={16} />Undo routine edit</button></section>
    {findings.length > 0 && <div className="logic-findings" aria-live="polite">{findings.map((i, n) => <p className={i.level} key={n}>{i.level === 'error' ? 'Fix before export: ' : 'Check timing: '}{i.message}</p>)}</div>}
    {!current ? <section className="panel routine-empty"><Blocks size={35} /><h2>Your first routine</h2><p>A command does one job. A routine combines those commands: collect a piece, pause, then score—or run independent mechanisms together.</p><div><button className="button primary" disabled={p.commands.length < 2} onClick={() => addRoutine(true)}>Start with two existing actions</button><button className="button" onClick={() => addRoutine()}>Start empty</button></div><small>The example uses your first two actions. Review their names, outputs, and timing before use.</small></section> : <>
      <section className="panel routine-settings"><label className="form-field"><span>Routine name</span><input aria-label="Routine name" maxLength={40} value={current.name} onChange={e => patch({ name: e.target.value })} /></label><label className="form-field"><span>Maximum total time (seconds)</span><input aria-label="Routine timeout" type="number" min={.05} max={15} step={.1} value={Number.isFinite(current.timeout) ? current.timeout : ''} onChange={e => patch({ timeout: e.target.valueAsNumber })} /></label><button className="icon-button danger" aria-label="Delete selected routine" onClick={() => { if (p.bindings.some(b => b.command === current.id) || p.auto.steps.some(s => s.type === 'command' && s.command === current.id)) { toast.error('Remove this routine from Controls and Autonomous first.'); return; } save(routines.filter(r => r.id !== current.id)); }}><Trash2 size={18} /></button></section>
      <div className="logic-layout"><section className="panel flow-workspace"><div className="panel-title"><div><h2>Routine blocks</h2><p>Top to bottom. Drag the grip or use the arrows to reorder.</p></div><span className="tag">{current.steps.length} / 16</span></div><div className="block-palette">{(Object.keys(stepLabels) as RoutineStep['type'][]).map(type => <button key={type} className="button" disabled={current.steps.length >= 16 || type === 'action' && !p.commands.length || !['action', 'wait'].includes(type) && independent.length < 2} onClick={() => addStep(type)}>{type === 'wait' ? <Clock3 size={16} /> : type === 'action' ? <Zap size={16} /> : <GitFork size={16} />}{stepLabels[type]}</button>)}</div>
        {!current.steps.length && <p className="flow-empty">Choose a block above to start. Together blocks become available when commands exist for two different subsystems.</p>}
        <ol className="flow-blocks">{current.steps.map((s, index) => <li key={s.id} className={'flow-block ' + s.type} onDragOver={e => { if (dragged) { e.preventDefault(); e.dataTransfer.dropEffect = 'move'; } }} onDrop={e => { e.preventDefault(); move(current.steps.findIndex(x => x.id === dragged), index); setDragged(null); }}>
          <div className="flow-block-heading"><span className="block-grip" draggable onDragStart={e => { setDragged(s.id); e.dataTransfer.setData('text/plain', s.id); e.dataTransfer.effectAllowed = 'move'; }} onDragEnd={() => setDragged(null)} title="Drag to reorder">⋮⋮</span><b>{index + 1}. {stepLabels[s.type]}</b><div><button className="icon-button" aria-label={`Move block ${index + 1} up`} disabled={index === 0} onClick={() => move(index, index - 1)}><ArrowUp size={16} /></button><button className="icon-button" aria-label={`Move block ${index + 1} down`} disabled={index === current.steps.length - 1} onClick={() => move(index, index + 1)}><ArrowDown size={16} /></button><button className="icon-button danger" aria-label={`Delete block ${index + 1}`} onClick={() => patch({ steps: current.steps.filter(x => x.id !== s.id) })}><Trash2 size={16} /></button></div></div>
          <p>{stepHelp[s.type]}</p>
          {s.type === 'wait' ? <label className="form-field"><span>Seconds</span><input aria-label={`Wait seconds block ${index + 1}`} type="number" min={.05} max={15} step={.1} value={Number.isFinite(s.seconds) ? s.seconds : ''} onChange={e => replaceStep(s.id, { ...s, seconds: e.target.valueAsNumber })} /></label> : s.type === 'action' ? <Pick label={`Action block ${index + 1}`} value={s.command} options={choices} onChange={command => replaceStep(s.id, { ...s, command })} /> : <div className="group-actions"><Pick label={`Finish rule block ${index + 1}`} value={s.type} options={(['parallel', 'race', 'deadline'] as const).map(value => ({ value, label: stepLabels[value] }))} onChange={type => replaceStep(s.id, { ...s, type: type as typeof s.type })} />{s.commands.map((id, n) => <div className="group-action" key={n}><span>{s.type === 'deadline' && n === 0 ? 'Lead' : n + 1}</span><Pick label={`Block ${index + 1} action ${n + 1}`} value={id} options={choices} onChange={value => replaceStep(s.id, { ...s, commands: s.commands.map((x, j) => j === n ? value : x) })} /><button className="icon-button" disabled={s.commands.length <= 2} aria-label={`Remove block ${index + 1} action ${n + 1}`} onClick={() => replaceStep(s.id, { ...s, commands: s.commands.filter((_, j) => n !== j) })}><Trash2 size={15} /></button></div>)}<button className="text-button" disabled={s.commands.length >= 8 || !p.commands.some(c => !s.commands.some(id => p.commands.find(x => x.id === id)?.subsystem === c.subsystem))} onClick={() => { const c = p.commands.find(c => !s.commands.some(id => p.commands.find(x => x.id === id)?.subsystem === c.subsystem)); if (c) replaceStep(s.id, { ...s, commands: [...s.commands, c.id] }); }}><Plus size={15} />Add independent action</button></div>}
          {stepCommands(s).map((id, n) => { const c = p.commands.find(c => c.id === id); return c && <div className="block-action-detail" key={n}><b>{c.name}</b><span>Output {c.output} · up to {c.timeout}s{c.untilDevice ? ' · sensor stop' : ''}</span></div>; })}
        </li>)}</ol><div className="flow-end">End → running outputs stop</div>
      </section><aside className="logic-side"><section className="panel routine-explainer"><h3>What this routine owns</h3><div className="device-tags">{routineRequirements(p, current).map(id => <span key={id}>{p.subsystems.find(s => s.id === id)?.name}</span>)}</div><p>These subsystems are reserved for the entire routine, including waits. A competing command can interrupt the routine.</p><p><b>{routineDuration(p, current).toFixed(2)}s</b> from configured action limits; capped at <b>{current.timeout}s</b>. Sensor stops can shorten it. This is a timing estimate, not a robot simulation.</p><p>An invalid sensor reading ends its action. Later blocks can still run; the routine is not a fault-handling sequence.</p><div className="routine-next"><button className="button" onClick={() => setTab('Controls')}>Assign a button <ArrowRight size={15} /></button><button className="button" onClick={() => setTab('Autonomous')}>Use in autonomous <ArrowRight size={15} /></button></div></section>
        <section className="panel routine-code"><div className="panel-title"><h2>See the generated code</h2><button className="icon-button" aria-label="Copy routine code" onClick={async () => { try { await navigator.clipboard.writeText(routineSource(current, language)); toast.success('Routine factory copied.'); } catch { toast.error('Clipboard unavailable. Select and copy the code below.'); } }}><Copy size={16} /></button></div><Tabs value={language} onValueChange={v => setLanguage(v as Project['language'])}><TabsList aria-label="Routine code language">{(['Java', 'C++', 'Python'] as const).map(l => <TabsTrigger value={l} key={l}>{l}</TabsTrigger>)}</TabsList></Tabs><p className="code-context">{language === 'Java' ? 'RobotContainer.java' : language === 'C++' ? 'Robot.cpp' : 'robot.py'} · class method preview</p><pre className="code-preview" tabIndex={0}><code>{routineSource(current, language)}</code></pre><p className="code-context">This factory is included in your export. Each action call creates a fresh command with its existing stop rules. Edit blocks here; source edits are not imported back.</p></section>
      </aside></div></>}
    <details className="panel logic-primer"><summary>How the pieces fit together</summary><div><p><b>Hardware</b> is what you wire. A <b>subsystem</b> groups a mechanism’s devices. A <b>command</b> gives that mechanism one bounded action. A <b>routine</b> combines actions. A button or an autonomous step starts it.</p><p>The visual builder uses WPILib command compositions. It does not provide arbitrary programming blocks, closed-loop mechanism control, or simulated physics.</p><a href="https://docs.wpilib.org/en/stable/docs/software/commandbased/command-compositions.html" target="_blank" rel="noreferrer">Learn about WPILib command compositions ↗</a></div></details>
  </div>;
}
