"use client";
import { ArrowRight, Boxes, Cable, Code2, Gamepad2, GitFork, Route, ShieldCheck, Zap } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { validate, benchChecks, type Project } from '@/lib/robot-model';
import { productById } from '@/lib/hardware-catalog';
import { availableActions, routineReferences, routineRequirements } from '@/lib/routines';

const countLabel=(count:number,noun:string)=>`${count} ${noun}${count===1?'':'s'}`;
export default function RobotMap({ project: p, setTab }: { project: Project; setTab: (s: string) => void }) {
  const errors = validate(p).filter(i => i.level === 'error');
  const next = errors[0];
  const actions = availableActions(p);
  const stages = [
    { title: '1. Connect', tab: 'Hardware', detail: countLabel(p.motors.length + (p.devices || []).length,'hardware record'), icon: Cable },
    { title: '2. Group', tab: 'Subsystems', detail: countLabel(p.subsystems.length,'subsystem'), icon: Boxes },
    { title: '3. Act', tab: 'Commands', detail: countLabel(p.commands.length,'individual command'), icon: Zap },
    { title: '4. Combine', tab: 'Logic builder', detail: countLabel((p.routines || []).length,'visual routine'), icon: GitFork },
    { title: '5. Trigger', tab: 'Controls', detail: countLabel(p.bindings.length,'button assignment'), icon: Gamepad2 },
    { title: '6. Verify', tab: 'Preflight', detail: `${Object.values(p.checks).filter(Boolean).length}/${benchChecks.length} bench checks`, icon: ShieldCheck },
  ];
  return <div className="view-stack robot-map"><div className="page-heading"><div><div className="eyebrow">YOUR ROBOT WORKSPACE</div><h1>From hardware to behavior.</h1><p>Follow each mechanism from its wiring to the action your driver starts.</p></div><button className="button primary" onClick={() => setTab('Development')}><GitFork size={17} />Continue development</button></div>
    <nav className="build-roadmap" aria-label="Robot build order">{stages.map(({ title, tab, detail, icon: Icon }) => <button key={tab} onClick={() => setTab(tab)}><Icon size={21} /><b>{title}</b><span>{detail}</span></button>)}</nav>
    <div className={'map-next ' + (errors.length ? 'needs-work' : '')}><div><b>{next ? 'Next: ' + next.message : 'Configuration checks passed'}</b><p>{next ? `${errors.length} issue${errors.length === 1 ? '' : 's'} to resolve before export.` : 'Build the generated project, test command behavior, then verify it on your robot.'}</p></div><button className="button" onClick={() => setTab(next && stages.some(s => s.tab === next.area) || next?.area === 'Code & export' || next?.area === 'Autonomous' ? next!.area : 'Preflight')}>{next ? 'Resolve issue' : 'Open checklist'}<ArrowRight size={16} /></button></div>
    <section className="panel mechanism-map"><div className="panel-title"><div><h2>Your mechanism map</h2><p>One home for each device. One owner for each action.</p></div><span className="tag">{p.language} · {p.team ? 'Team ' + p.team : 'Team number needed'}</span></div><Accordion type="multiple" defaultValue={p.subsystems.map(s => s.id)}>{p.subsystems.map(s => {
      const motors = p.motors.filter(m => m.subsystem === s.id), devices = (p.devices || []).filter(d => d.subsystem === s.id), commands = p.commands.filter(c => c.subsystem === s.id);
      const routines = (p.routines || []).filter(r => routineRequirements(p, r).includes(s.id));
      return <AccordionItem key={s.id} value={s.id}><AccordionTrigger><span className="map-mechanism-name"><Boxes size={19} /><b>{s.name}</b><small>{countLabel(motors.length + devices.length,'device')} · {countLabel(commands.length,'action')}</small></span></AccordionTrigger><AccordionContent><div className="mechanism-columns"><div><h3>Hardware</h3>{motors.map(m => <button className="map-item" key={m.id} onClick={() => setTab('Hardware')}><Cable size={15} /><span><b>{m.name}</b><small>{m.type.startsWith('PWM') ? `PWM ${m.can}` : `${m.bus || 'rio'} · CAN ${m.can}`} · {m.type}</small></span></button>)}{devices.map(d => { const def = productById(d.product); return <button className="map-item" key={d.id} onClick={() => setTab('Hardware')}><Cable size={15} /><span><b>{d.name}</b><small>{def?.name} · {def?.adapter === 'custom' ? 'integration needed' : def?.adapter === 'passive' ? 'wiring record' : 'code adapter'}</small></span></button>; })}{!motors.length && !devices.length && <p>No devices assigned.</p>}<button className="text-button" onClick={() => setTab('Hardware')}>Configure hardware <ArrowRight size={14} /></button></div>
      <div><h3>Actions</h3>{s.id === 'drive' && <><div className="map-item"><Gamepad2 size={15} /><span><b>Arcade drive</b><small>Driver axes · {Math.round(p.controls.maxOutput * 100)}% output cap</small></span></div><button className="map-item" onClick={() => setTab('Autonomous')}><Route size={15} /><span><b>{p.auto.name}</b><small>Path following · {p.drive.gyro} heading</small></span></button></>}{commands.map(c => <button className="map-item" key={c.id} onClick={() => setTab('Commands')}><Zap size={15} /><span><b>{c.name}</b><small>{c.device ? devices.find(d => d.id === c.device)?.name || 'Missing device' : 'Subsystem motors'} · output {c.output} · ≤ {c.timeout}s</small>{c.untilDevice && <small>Stops on {(p.devices || []).find(d => d.id === c.untilDevice)?.name || 'missing sensor'}</small>}</span></button>)}{s.id !== 'drive' && !commands.length && <p>No actions yet.</p>}<button className="text-button" onClick={() => setTab(s.id === 'drive' ? 'Controls' : 'Commands')}>{s.id === 'drive' ? 'Edit drive controls' : 'Create or edit actions'} <ArrowRight size={14} /></button></div>
      <div><h3>Where they run</h3>{routines.map(r => <button className="map-item" key={r.id} onClick={() => setTab('Logic builder')}><GitFork size={15} /><span><b>{r.name}</b><small>{r.steps.length} blocks · ≤ {r.timeout}s</small></span></button>)}{commands.map(c => { const bindings = p.bindings.filter(b => b.command === c.id); const auto = p.auto.steps.some(step => step.type === 'command' && step.command === c.id); return <div className="map-usage" key={c.id}><b>{c.name}</b><span>{[...bindings.map(b => `${b.controller} button ${b.button}`), ...(auto ? ['autonomous'] : []), ...routineReferences(p, c.id).map(r => r.name)].join(' · ') || 'Not assigned yet'}</span></div>; })}{s.id === 'drive' && <p>Driver sticks in teleop. The selected route in autonomous.</p>}<button className="text-button" onClick={() => setTab('Logic builder')}>Combine actions <ArrowRight size={14} /></button></div></div></AccordionContent></AccordionItem>;
    })}</Accordion></section>
    <div className="subsystem-grid"><section className="panel map-triggers"><div className="panel-title"><h2><Gamepad2 size={20} />Driver & operator</h2><button className="text-button" onClick={() => setTab('Controls')}>Edit <ArrowRight size={15} /></button></div>{p.bindings.map(b => <div className="map-binding" key={b.id}><span>{b.controller} · button {b.button}</span><ArrowRight size={15} /><b>{actions.find(a => a.value === b.command)?.label || 'Missing action'}</b><small>{b.behavior === 'whileHeld' ? 'while held' : b.behavior === 'toggle' ? 'toggle' : 'on press'}</small></div>)}{!p.bindings.length && <p className="map-empty">No buttons assigned yet.</p>}</section><section className="panel map-triggers"><div className="panel-title"><h2><Route size={20} />Autonomous order</h2><button className="text-button" onClick={() => setTab('Autonomous')}>Edit <ArrowRight size={15} /></button></div><ol className="map-auto">{p.auto.steps.map(s => <li key={s.id}>{s.type === 'path' ? `Follow ${p.auto.name}` : s.type === 'wait' ? `Wait ${s.seconds}s` : actions.find(a => a.value === s.command)?.label || 'Missing action'}</li>)}</ol><p className="map-empty">“Do nothing” stays the default robot choice until a routine is selected on the dashboard.</p></section></div>
    <section className="map-handoff"><Code2 size={25} /><div><h2>Visual plan → readable robot code</h2><p>One saved project generates Java, C++, or Python. Each archive includes a hardware guide and a behavior map for students and mentors.</p></div><button className="button" onClick={() => setTab('Code & export')}>Review code & build <ArrowRight size={16} /></button></section>
  </div>;
}
