import { subsystemLayoutSchema } from './subsystem-layout';
import { drivetrainFields,validateDrivetrain } from './drivetrain';
import { z } from 'zod';
import { routineSchema,validateRoutines,availableActions } from './routines';
import { deviceSchema,busName } from './hardware-catalog';
import { validateHardware } from './hardware-validation';
import { librarySettingsSchema,validateLibraryLock } from './libraries';
export const versions={wpilib:'2026.2.1',robotpy:'2026.2.2',rev:'2026.0.5',robotpyRev:'2026.0.4',phoenix:'26.3.0',pathplanner:'2026.1.2',checked:'2026-09-28'};
const id=z.string().regex(/^[A-Za-z][A-Za-z0-9_]{0,39}$/);
const finite=z.number().finite();
export const motorSchema=z.object({id,name:z.string().min(1).max(60),type:z.enum(['SparkMax','SparkFlex','TalonFX','TalonFXS','TalonSRX','VictorSPX','ThriftyNova','PWMSparkMax','PWMTalonSRX','PWMVictorSPX','PWMSpark','PWMVictor']),bus:busName.optional(),motorKind:z.enum(['default','brushed','neo','vortex','minion','falcon']).optional(),can:finite.int().min(0).max(62),inverted:z.boolean(),sensorSign:z.union([z.literal(1),z.literal(-1)]),current:finite.int().min(1).max(80),subsystem:id,role:z.enum(['left','right','mechanism','wheel','steer']),limit:finite.int().min(-1).max(9)}).strict();
export const projectSchema=z.object({schema:z.literal(1),name:z.string().min(1).max(60),team:finite.int().min(0).max(99999),language:z.enum(['Java','C++','Python']),motors:z.array(motorSchema).max(40),subsystems:z.array(z.object({id,name:z.string().min(1).max(40),description:z.string().max(200),layout:subsystemLayoutSchema.optional()})).min(1).max(20),devices:z.array(deviceSchema).max(80).optional(),routines:z.array(routineSchema).max(20).optional(),commands:z.array(z.object({id,device:id.optional(),untilDevice:id.optional(),condition:z.enum(['above','below']).optional(),threshold:finite.optional(),name:z.string().min(1).max(40),subsystem:id,output:finite.min(-1).max(1),timeout:finite.min(.05).max(15)})).max(30),bindings:z.array(z.object({id,controller:z.enum(['driver','operator']),button:finite.int().min(1).max(20),command:id,behavior:z.enum(['whileHeld','onPress','toggle'])})).max(40),controls:z.object({driveStyle:z.enum(['arcade','tank']).optional(),strafeAxis:finite.int().min(0).max(11).optional(),strafeSign:z.union([z.literal(1),z.literal(-1)]).optional(),rightAxis:finite.int().min(0).max(11).optional(),rightSign:z.union([z.literal(1),z.literal(-1)]).optional(),fieldRelative:z.boolean().optional(),driverPort:finite.int().min(0).max(5),operatorPort:finite.int().min(0).max(5),driverType:z.enum(['Xbox','Joystick']),operatorType:z.enum(['Xbox','Joystick']),forwardAxis:finite.int().min(0).max(11),turnAxis:finite.int().min(0).max(11),forwardSign:z.union([z.literal(1),z.literal(-1)]),turnSign:z.union([z.literal(1),z.literal(-1)]),deadband:finite.min(0).max(.3),maxOutput:finite.min(.05).max(1)}),drive:z.object({...drivetrainFields,trackWidth:finite.min(.2).max(2),wheelDiameter:finite.min(.04).max(.5),gearing:finite.min(1).max(40),maxSpeed:finite.min(.1).max(8),mass:finite.min(5).max(100),moi:finite.min(.1).max(30),kS:finite.min(0).max(3),kV:finite.min(.1).max(20),kP:finite.min(0).max(20),gyro:z.enum(['ADXRS450','Pigeon2','NavX']),gyroBus:busName.optional(),navxInterface:z.enum(['mxp','usb1','usb2','onboard']).optional(),gyroCan:finite.int().min(0).max(62)}),auto:z.object({name:id,maxSpeed:finite.min(.1).max(6),maxAcceleration:finite.min(.1).max(6),waypoints:z.array(z.object({x:finite.min(0).max(16.54),y:finite.min(0).max(8.07)})).min(2).max(30),steps:z.array(z.object({id,type:z.enum(['path','command','wait']),command:z.string().max(40),seconds:finite.min(.05).max(15)})).max(20)}),checks:z.record(z.boolean()),libraries:librarySettingsSchema.optional()}).strict();
export type Project=z.infer<typeof projectSchema>;export type Motor=z.infer<typeof motorSchema>;export type Issue={level:'error'|'warning',area:string,message:string;subsystems?:string[]};
export const initialProject:Project={schema:1,name:'My competition robot',team:0,language:'Java',motors:[{id:'leftFront',name:'Left front',can:1,role:'left',subsystem:'drive',inverted:false,sensorSign:1},{id:'leftRear',name:'Left rear',can:2,role:'left',subsystem:'drive',inverted:false,sensorSign:1},{id:'rightFront',name:'Right front',can:3,role:'right',subsystem:'drive',inverted:true,sensorSign:-1},{id:'rightRear',name:'Right rear',can:4,role:'right',subsystem:'drive',inverted:true,sensorSign:-1},{id:'intakeMotor',name:'Intake motor',can:5,role:'mechanism',subsystem:'intake',inverted:false,sensorSign:1},{id:'shooterMotor',name:'Shooter motor',can:6,role:'mechanism',subsystem:'shooter',inverted:false,sensorSign:1}].map(m=>({...m,type:'SparkMax',current:30,limit:-1})) as Motor[],subsystems:[{id:'drive',name:'Drivetrain',description:'Differential drive with encoder odometry and gyro heading.'},{id:'intake',name:'Intake',description:'Collect game pieces while the button is held.'},{id:'shooter',name:'Shooter',description:'Open-loop shooter. Tune output on your robot.'}],commands:[{id:'collect',name:'Collect',subsystem:'intake',output:.35,timeout:3},{id:'shoot',name:'Shoot',subsystem:'shooter',output:.5,timeout:2}],bindings:[{id:'binding1',controller:'driver',button:1,command:'collect',behavior:'whileHeld'},{id:'binding2',controller:'operator',button:6,command:'shoot',behavior:'whileHeld'}],controls:{driverPort:0,operatorPort:1,driverType:'Xbox',operatorType:'Xbox',forwardAxis:1,turnAxis:4,forwardSign:-1,turnSign:-1,deadband:.08,maxOutput:.35},drive:{trackWidth:.6,wheelDiameter:.1524,gearing:10.71,maxSpeed:3,mass:55,moi:6,kS:.2,kV:2.4,kP:1,gyro:'ADXRS450',gyroCan:20},auto:{name:'LeaveStart',maxSpeed:1,maxAcceleration:1,waypoints:[{x:1.5,y:4},{x:3.2,y:4},{x:4.8,y:3.1}],steps:[{id:'step1',type:'path',command:'',seconds:1}]},checks:{}};
/** A new draft has no example hardware. Existing saved projects are loaded unchanged. */
export function createDraft():Project { return {...structuredClone(initialProject),name:'My robot',motors:[],subsystems:[{id:'drive',name:'Drivetrain',description:''}],commands:[],bindings:[],devices:[],auto:{...structuredClone(initialProject.auto),steps:[]},checks:{}}; }
export const benchChecks=[['mechanical','Robot is supported; mechanisms are clear and secured.'],['can','CAN IDs, firmware, wiring, and termination are verified.'],['direction','Drive output and encoder signs agree with forward motion.'],['gyro','Gyro heading and odometry are verified on the robot.'],['limits','Motor current limits and active-low limit switches are tested.'],['tuning','Wheel geometry, feedforward, feedback, and path constraints are tuned.'],['disable','Disable, button release, command timeout, and autonomous interruption stop outputs.'],['simulation','Project compiles and the command flow passes simulation.'],['field','Autonomous is tested at reduced speed on the actual field layout.']];
export function validate(p:Project):Issue[]{const issues:Issue[]=[];const error=(area:string,message:string,subsystems?:string[])=>issues.push({level:'error',area,message,...(subsystems?{subsystems}:{})});const warn=(area:string,message:string)=>issues.push({level:'warning',area,message});const shape=projectSchema.safeParse(p);if(!shape.success){shape.error.issues.forEach(i=>error('Configuration',`${i.path.join(' → ')}: ${i.message}`));return issues;}
if(p.libraries){try{validateLibraryLock(p.libraries.lock);if(p.libraries.previous)validateLibraryLock(p.libraries.previous);}catch(e){error('Libraries & updates',e instanceof Error?e.message:'Invalid library lock.');}}
if(p.team<1)error('Code & export','Enter your real team number before exporting robot code.');
issues.push(...validateHardware(p),...validateRoutines(p));p.motors.forEach(m=>{if(!p.subsystems.some(s=>s.id===m.subsystem))error('Hardware',m.name+' references a missing subsystem.',[m.subsystem]);if((m.role==='mechanism')===(m.subsystem==='drive'))error('Hardware',m.name+': drivetrain motors need a drive role; mechanisms need a mechanism role.',[m.subsystem]);});
issues.push(...validateDrivetrain(p)); const ports=p.motors.filter(m=>m.limit>=0).map(m=>m.limit);if(new Set(ports).size!==ports.length)error('Hardware','Each limit switch needs a unique DIO channel.',p.motors.filter(m=>m.limit>=0&&ports.filter(port=>port===m.limit).length>1).map(m=>m.subsystem));
for(const group of [p.motors,p.subsystems,p.commands,p.bindings,p.auto.steps])if(new Set(group.map(x=>x.id)).size!==group.length)error('Configuration','Duplicate internal identifiers were found.');
p.commands.forEach(c=>{if(c.subsystem==='drive')error('Commands','Drive actions belong in autonomous paths, not mechanism commands.',[c.subsystem]);if(!p.subsystems.some(s=>s.id===c.subsystem))error('Commands',`${c.name} references a missing subsystem.`,[c.subsystem]);if(!c.device&&!p.motors.some(m=>m.subsystem===c.subsystem))error('Commands',`${c.name} has no motors assigned.`,[c.subsystem]);});
const binds=new Set<string>();p.bindings.forEach(b=>{const key=`${b.controller}:${b.button}`;if(binds.has(key))error('Controls',`${b.controller} button ${b.button} has multiple assignments.`);binds.add(key);if(!availableActions(p).some(c=>c.value===b.command))error('Controls','A button refers to a deleted command.');if(p.controls[`${b.controller}Type`]==='Xbox'&&b.button>10)error('Controls','Xbox buttons must be 1–10.');});if(p.controls.driverPort===p.controls.operatorPort)error('Controls','Driver and operator USB ports must differ.');
p.auto.waypoints.forEach((w,i)=>{if(i&&Math.hypot(w.x-p.auto.waypoints[i-1].x,w.y-p.auto.waypoints[i-1].y)<.1)error('Autonomous','Waypoints must be at least 0.1 m apart.');});if(p.auto.maxSpeed>p.drive.maxSpeed)error('Autonomous','Path speed exceeds the drivetrain maximum speed.');if(p.auto.steps.filter(s=>s.type==='path').length>1)error('Autonomous','This route can appear once in the sequence; duplicate it in PathPlanner for multi-path routines.');p.auto.steps.forEach(s=>{if(s.type==='command'&&!availableActions(p).some(c=>c.value===s.command))error('Autonomous','An autonomous step refers to a missing command.');});
if(!p.auto.steps.length)warn('Autonomous','No autonomous steps are configured. The robot will remain stopped.');
warn('Preflight','Generated source requires a local WPILib build, motor-direction verification, tuning, and on-robot testing.');if(benchChecks.some(([key])=>!p.checks[key]))warn('Preflight','Complete the bench and field checklist before competition.');return issues;}
export const uid=(prefix:string)=>prefix+Math.random().toString(36).slice(2,9);
export function parseProject(text:string):Project{return projectSchema.parse(JSON.parse(text));}
